# This is a basic workflow to help you get started with Actions

name: Publish on modrinth

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run the resource pack packager
        run: |
          cd $GITHUB_WORKSPACE
          python3 distribute.py
      
      - name: Upload to the GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ComputerCreate.zip
          asset_name: ComputerCreate.zip
          asset_content_type: application/gzip
      
      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file_path: ./ComputerCreate.zip
          name: ComputerCreate ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          game_versions: 1.18
          release_type: beta
          featured: true
          project_id: PtgHJyfu
          loaders: minecraft
