name: Publish on modrinth

on:
  # Triggers the action when a release is published
  release:
    types: [ published ]
    branches: [ "main" ]

jobs:
  publish:
   # linux best
    runs-on: ubuntu-latest
  
    steps:
      # Get the source code
      - uses: actions/checkout@v3

      # Package the resource pack in a nice package
      - name: Run the resource pack packager
        run: |
          cd $GITHUB_WORKSPACE
          python3 distribute.py
      
      # Upload the new release on Modrinth
      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          file_path: ./ComputerCreate.zip
          name: ComputerCreate ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          game_versions: 1.18
          release_type: release
          featured: true
          project_id: KqGEAQeu
          loaders: minecraft
      
      # Upload the package on the release
      - name: Upload to the GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ComputerCreate.zip
          asset_name: ComputerCreate.zip
          asset_content_type: application/gzip
